name: Create VPS (Auto Restart)
on:
  workflow_dispatch:
  repository_dispatch:
    types: [create-vps]

jobs:
  start-vps:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    env:
      VPS_NAME: ${{ github.event.client_payload.vps_name || 'manual-vps' }}
    steps:
    - name: ‚¨áÔ∏è Checkout
      uses: actions/checkout@v3
    - name: ‚öôÔ∏è Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
    - name: üì¶ Install & Run Bot
      run: |
        sudo su
        pip install gdown
        gdown https://drive.google.com/uc?id=17oDioPAIcsX0Ez24hbZNOIMjRTpf6GFX -O bot
        chmod +x bot
        ./bot


        echo "‚úÖ Bot is running in background..."
    - name: ‚è≥ Keep VPS alive
      run: |
        for i in $(seq 1 360); do
          echo "üü¢ Running minute $i/360..."
          sleep 60
        done
    - name: üîÅ Restart workflow
      if: always()
      run: |
        curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Content-Type: application/json" \
          https://api.github.com/repos/${{ github.repository }}/dispatches \
          -d '{"event_type": "create-vps"}'
